# SPDX-FileCopyrightText: Copyright The Lima Authors
# SPDX-License-Identifier: Apache-2.0

name: "Set up SSH (Deprecated, as the feature is merged into `setup` action)"
description: "Set up SSH (Deprecated, as the feature is merged into `setup` action)"
runs:
  using: "composite"
  steps:
    - name: "NOP"
      id: setup-ssh
      shell: bash
      run: echo "::warning::lima-vm/lima-actions/ssh is deprecated, as the feature is merged into lima-vm/lima-actions/setup."